Adding jprod_residual! and jtprod_residual!
JuliaSmoothOptimizers/BundleAdjustmentModels.jl pull request #64
Opened 2022-07-11 21:59 UTC by AntoninKns

Adding a workaround of ``jprod_residual!`` and ``jtprod_residual!`` in order for BundleAdjustmentModels to work better with other packages from JSO. The true detailed version of ``jprod_residual!`` and ``jtprod_residual!`` should be added later in order to avoid allocations and have better performance for these functions.

2022-07-11 22:14 UTC, dpo commented
I don't think this is a good idea. This is going to be so much slower than what you have now.

2022-07-11 22:20 UTC, AntoninKns commented
@tmigot asked me to add them in case these functions are called by other JSO packages at least it won't crash. I'll let him correct me, I might not have understood the reasons well.

2022-07-11 22:27 UTC, AntoninKns commented
If you think it's worth the time I can directly implement the ``jprod_residual!`` and ``jtprod_residual!`` manually based on the jacobian description.

2022-07-11 22:53 UTC, tmigot commented
I asked Antonin this, so that we can use the package. I get that this is a very basic version (and not efficient), but we can improve it later when Antonin is further advanced with his project.

2022-07-29 21:01 UTC, dpo commented
Let's at least have a caching system for the Jacobian: only evaluate it if `x` changes. You should be able to compute the `shasum` of `x` and compare that instead of checking each component, and only be wrong with probability ε.

2022-07-29 21:02 UTC, dpo requested changes
Let's at least have a caching system for the Jacobian: only evaluate it if `x` changes. You should be able to compute the `shasum` of `x` and compare that instead of checking each component, and only be wrong with probability ε.

2025-03-20 03:19 UTC, amontoison commented
`jac_coord_residual!` is not correct and the PR was not updated since 3 years.
I will close the PR and add `jprod_residual!` and `jtprod_residual!` with `ADNLPModels.jl`.

2025-03-20 03:19 UTC, closed without merging