Replaced CITATION.bib by CITATION.cff
JuliaSmoothOptimizers/BundleAdjustmentModels.jl pull request #87
Opened 2024-02-03 20:01 UTC by Jay-sanjay

This PR address #86 

closes #86

2024-02-06 20:02 UTC, tmigot requested changes
Thanks @Jay-sanjay for the suggestion, hère are some comments

2024-02-06 20:02 UTC, tmigot commented on CITATION.cff
> +doi: "10.5281/zenodo.5167631"
```suggestion
keywords:
  - Least squares
  - Julia
  - Bundle Adjustment
identifiers:
  - description: Zenodo archive
    type: doi
    value: 10.5281/zenodo.5167631
```

2024-02-06 21:00 UTC, Jay-sanjay commented
Thank you for the suggestions sir.

2024-02-06 21:31 UTC, tmigot commented
Could you also update the links in the readme.md and https://github.com/Jay-sanjay/BundleAdjustmentModels.jl/blob/cff/docs/src/index.md to point to CFF and not BIB?

2024-02-09 21:02 UTC, tmigot commented
@software{Kenens_BundleAdjustmentModels_jl_Julia_repository_2023,
author = {Kenens, Antonin and Orban, Dominique and {contributors}},
license = {MPL-2.0},
month = mar,
title = {{BundleAdjustmentModels.jl: Julia repository of bundle adjustment problems}},
url = {https://github.com/JuliaSmoothOptimizers/BundleAdjustmentModels.jl},
version = {0.3.2},
year = {2023}
}

2024-02-09 21:14 UTC, tmigot approved these changes
Thank you!

2024-02-09 21:14 UTC, merged